# Generated by Django 6.0.3 on 2026-03-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_loginattempt_useractivity_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='supplier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered from Supplier'), ('shipped', 'Shipped by Supplier'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
